---
-
  name: Deploy istio components
  shell: "oc apply -f {{ istio_tmp_folder }}/istio.yaml -n {{ istio_namespace }}"
  failed_when: no

-
  name: Include istio update stuff tasks
  include_tasks: update-deployment-data.yml

-
  include_role:
    name: openshift-utils
    tasks_from: wait-for-deployment.yml
  vars:
    name: "{{ item.name }}"
    ns: "{{ istio_namespace }}"
    desired: "{{ item.replicas }}"
    ready: "{{ item.ready_replicas }}"
  with_items: "{{ istio_deployments }}"
