---
-
  name: Deploy knative-serving components
  shell: "oc apply -f {{ knative_serving_tmp_folder }}/release-lite.yaml -n {{ knative_serving_namespace }}"
  failed_when: no

-
  name: Include knative-serving update stuff tasks
  include_tasks: update-deployment-data.yml

-
  include_role:
    name: openshift-utils
    tasks_from: wait-for-deployment.yml
  vars:
    name: "{{ item.name }}"
    ns: "{{ knative_serving_namespace }}"
    desired: "{{ item.replicas }}"
    ready: "{{ item.ready_replicas }}"
  with_items: "{{ knative_serving_deployments }}"
